# Generated by Django 4.1.4 on 2023-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAPI', '0004_alter_image_slug_delete_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
