# Generated by Django 4.1.4 on 2023-01-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageAPI', '0005_remove_image_id_alter_image_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='imagesAPI'),
        ),
    ]
